
# coding: utf-8

# In[ ]:


test.loc[test['Name'].str.contains('Шоколадница'), 'Name'] = 'Шоколадница'
test.loc[test['Name'].str.contains('ШОКОЛАДНИЦА'), 'Name'] = 'Шоколадница'
test.loc[test['Name'].str.contains('Хлеб насущный'), 'Name'] = 'Хлеб насущный'
test.loc[test['Name'].str.contains('Хлеб Насущный'), 'Name'] = 'Хлеб насущный'
test.loc[test['Name'].str.contains('ХЛЕБ НАСУЩНЫЙ'), 'Name'] = 'Хлеб насущный'
test.loc[test['Name'].str.contains('Starbucks'), 'Name'] = 'Starbucks'
test.loc[test['Name'].str.contains('Старбак'), 'Name'] = 'Starbucks'
test.loc[test['Name'].str.contains('Чайхона №1'), 'Name'] = 'Чайхона №1'
test.loc[test['Name'].str.contains('Кофе Хаус'), 'Name'] = 'Кофе Хаус'
test.loc[test['Name'].str.contains('КОФЕ ХАУС'), 'Name'] = 'Кофе Хаус'
test.loc[test['Name'].str.contains('KFC'), 'Name'] = 'KFC'
test.loc[test['Name'].str.contains('КФС'), 'Name'] = 'KFC'
test.loc[test['Name'].str.contains('Прайм'), 'Name'] = 'Прайм стар'
test.loc[test['Name'].str.contains('ПРАЙМ'), 'Name'] = 'Прайм стар'
test.loc[test['Name'].str.contains('PRIME'), 'Name'] = 'Прайм стар'
test.loc[test['Name'].str.contains('Бургер Кинг'), 'Name'] = 'Burger King'
test.loc[test['Name'].str.contains('Domino'), 'Name'] = 'Dominos Pizza'
test.loc[test['Name'].str.contains('Домино'), 'Name'] = 'Dominos Pizza'
test.loc[test['Name'].str.contains('Караваевы'), 'Name'] = 'Кулинарная лавка братьев Караваевых'
test.loc[test['Name'].str.contains('Патио'), 'Name'] = 'Il Patio'
test.loc[test['Name'].str.contains('Патио'), 'Name'] = 'Il Patio'
test.loc[test['Name'].str.contains('PATIO'), 'Name'] = 'Il Patio'
test.loc[test['Name'].str.contains('МУ-МУ'), 'Name'] = 'Му-Му'
test.loc[test['Name'].str.contains('Му-Му'), 'Name'] = 'Му-Му'
test.loc[test['Name'].str.contains('Му Му'), 'Name'] = 'Му-Му'
test.loc[test['Name'].str.contains('МУ МУ'), 'Name'] = 'Му-Му'
test.loc[test['Name'].str.contains('ТЕРЕМОК'), 'Name'] = 'Теремок'
test.loc[test['Name'].str.contains('Крошка картошка'), 'Name'] = 'Крошка Картошка'
test.loc[test['Name'].str.contains('КРОШКА КАРТОШКА'), 'Name'] = 'Крошка Картошка'
test.loc[test['Name'].str.contains('Макд'), 'Name'] = 'Макдоналдс'
test.loc[test['Name'].str.contains('donald'), 'Name'] = 'Макдоналдс'
test.loc[test['Name'].str.contains('ДОНАЛ'), 'Name'] = 'Макдоналдс'
test.loc[test['Name'].str.contains('донал'), 'Name'] = 'Макдоналдс'
test.loc[test['Name'].str.contains('Азбука Вкуса'), 'Name'] = 'Азбука вкуса'
test.loc[test['Name'].str.contains('Дабл Би'), 'Name'] = 'Даблби'
test.loc[test['Name'].str.contains('Даблби'), 'Name'] = 'Даблби'
test.loc[test['Name'].str.contains('Дабл би'), 'Name'] = 'Даблби'
test.loc[test['Name'].str.contains('Кафе Хинкальная'), 'Name'] = 'Кафе «Хинкальная»'
test.loc[test['Name'].str.contains('Планета Суши'), 'Name'] = 'Планета суши'
test.loc[test['Name'].str.contains('Планета суши'), 'Name'] = 'Планета суши'
test.loc[test['Name'].str.contains('ПЛАНЕТА СУШИ'), 'Name'] = 'Планета суши'
test.loc[test['Name'].str.contains('Якитория'), 'Name'] = 'Якитория'
test.loc[test['Name'].str.contains('ЯКИТОРИЯ'), 'Name'] = 'Якитория'
test.loc[test['Name'].str.contains('КОРЧМА ТАРАС БУЛЬБА'), 'Name'] = 'Корчма Тарас Бульба'
test.loc[test['Name'].str.contains('чма Тарас'), 'Name'] = 'Корчма Тарас Бульба'
test.loc[test['Name'].str.contains('Бульба'), 'Name'] = 'Корчма Тарас Бульба'
test.loc[test['Name'].str.contains('КОФЕМАНИЯ'), 'Name'] = 'Кофемания'
test.loc[test['Name'].str.contains('Goodman'), 'Name'] = 'Goodman'
test.loc[test['Name'].str.contains('GOODMAN'), 'Name'] = 'Goodman'
test.loc[test['Name'].str.contains('Гудман'), 'Name'] = 'Goodman'
test.loc[test['Name'].str.contains('ДВЕ ПАЛОЧКИ'), 'Name'] = 'Две палочки'
test.loc[test['Name'].str.contains('BBBurgers'), 'Name'] = 'BB&Burgers'
test.loc[test['Name'].str.contains('В&В'), 'Name'] = 'BB&Burgers'
test.loc[test['Name'].str.contains('BB'), 'Name'] = 'BB&Burgers'
test.loc[test['Name'].str.contains('ББ и Бургерс'), 'Name'] = 'BB&Burgers'
test.loc[test['Name'].str.contains('Папа Джонс'), 'Name'] = 'Папа Джонс'
test.loc[test['Name'].str.contains('Бизон'), 'Name'] = 'Стейкхаус "Бизон"'
test.loc[test['Name'].str.contains('Frayda'), 'Name'] = 'TGI Fraydas'
test.loc[test['Name'].str.contains('АКАДЕМИЯ'), 'Name'] = 'Пиццерия "Академия"'
test.loc[test['Name'].str.contains('Академия'), 'Name'] = 'Пиццерия "Академия"'
test.loc[test['Name'].str.contains('БУТЧЕР'), 'Name'] = 'Бутчер'
test.loc[test['Name'].str.contains('Сабвей'), 'Name'] = 'Subway'

