"""Build both Markdown reports and README from the executed notebook's exported results.

    python scripts/build_markdown_reports.py
"""



from build_report_page import ROOT, TYPES_RU, effect_label, load, shortlist_2026

REPORT = ROOT / "report"
STATION_SOURCE = "https://www.metrostroy.ru/projects/1059-lefortovo-severo-vostochnyj-uchastok-tpk/"


def table(headers, rows):
    def clean(value):
        return str(value).replace("|", "\\|").replace("\n", " ")

    return "\n".join([
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
        *("| " + " | ".join(clean(v) for v in row) + " |" for row in rows),
    ])


def percent(value):
    return f"{100 * value:.0f}%"


def short_table(scores, year, ru):
    rows = scores[scores[f"rank_{year}"].notna()].sort_values(f"rank_{year}")
    headers = (["№", "Участок / станция", "Записей", "Прогноз", "Оценка", "Допуск", "В десятке", "Прогноз 10–90%"]
               if ru else ["Rank", "Area / station", "Recorded", "Prediction", "Score", "Eligible",
                           "Top 10", "10–90% prediction"])
    return table(headers, [
        [int(row[f"rank_{year}"]), f"{row['address']} / {row[f'nearest_metro_{year}']}",
         int(row[f"competitors_{year}"]), f"{row[f'expected_{year}']:.2f}", f"{row[f'score_{year}']:.3f}",
         percent(row[f"eligibility_frequency_{year}"]), percent(row[f"top10_frequency_{year}"]),
         f"{row[f'expected_p10_{year}']:.2f}–{row[f'expected_p90_{year}']:.2f}"]
        for _, row in rows.iterrows()
    ])


def excluded_table(scores, ru):
    rows = scores[(~scores["eligible_2026"]) & (scores["score_2026"] < 0)]
    rows = rows.sort_values("score_2026", kind="stable").head(5)
    return table(
        ["Участок / станция", "Оценка", "Допуск"] if ru else ["Area / station", "Score", "Eligible"],
        [[f"{row['address']} / {row['nearest_metro_2026']}", f"{row['score_2026']:.3f}",
          percent(row["eligibility_frequency_2026"])] for _, row in rows.iterrows()],
    )


def effects_table(summary, ru):
    return table(
        ["Переход", "Контраст прогноза", "95% условный интервал"] if ru
        else ["Contrast", "Prediction change", "95% conditional interval"],
        [[effect_label(key, row) if ru else row["change"], f"{row['effect, %']:+.2f}%",
          f"{row['95% low']:+.2f}% … {row['95% high']:+.2f}%"] for key, row in summary["effects"].items()],
    )


def source_table(summary, ru):
    return table(
        ["Квинтиль остатка 2019", "Участков", "Реестр 2019", "OSM 2026", "Отношение сумм"] if ru
        else ["2019 residual quintile", "Cells", "2019 register", "2026 OSM", "Ratio of sums"],
        [[i, row["cells"], row["venues_2019"], row["venues_2026"], f"{row['change']:.3f}"]
         for i, row in enumerate(summary["look_forward"]["by_quintile"], 1)],
    )


def type_table(summary, ru):
    return table(
        ["Тип", "Участков", "Реестр 2019", "OSM 2026"] if ru else ["Type", "Cells", "2019 register", "2026 OSM"],
        [[TYPES_RU[name] if ru else name, row["cells"], row["venues_2019"], row["venues_2026"]]
         for name, row in summary["look_forward"]["by_type"].items()],
    )


def interval(summary, prefix):
    look = summary["look_forward"]
    return ", ".join(f"{100 * (2 ** look[key] - 1):+.2f}%"
                     for key in (prefix, f"{prefix}_low", f"{prefix}_high"))


def build_report(summary, scores, ru):
    v, now = summary["validation"], summary["now"]
    repeated_range = lambda values: "–".join(f"{x:.3f}" for x in values)  # noqa: E731
    robust = [row for row in shortlist_2026(summary, scores) if row["robust"]]
    robust_names = "; ".join(f"#{row['rank']} {row['cell']['nearest_metro_2026']}" for row in robust) or "—"
    benchmark = table(["Model", "D², seed 0"], [[k, f"{value:.3f}"] for k, value in summary["model_d2"].items()])
    runtime = ", ".join(f"{key} {value}" for key, value in summary.get("runtime", {}).items())
    if ru:
        return f"""<!-- Generated by scripts/build_markdown_reports.py; edit the builder, not this file. -->
# Кафе в центре Москвы: модель счётчиков и участки для проверки

Модель описывает число **записанных в источнике** кафе и ресторанов на 364 участках в радиусе
6 км от Красной площади. Отрицательный остаток означает, что записей меньше прогноза по наблюдаемому
окружению. Он не доказывает неудовлетворённый спрос, наличие помещения или прибыльность нового кафе.
Итог — список для проверки данных и посещения участков, а не рекомендация заключать договор аренды.

## Данные и границы сопоставимости

Используются городской реестр 2019 года и снимок OpenStreetMap от **{summary['osm_date']}**.
В радиусе 6 км источники содержат {summary['competitors_within_6km']:,} и {now['competitors_within_6km']:,}
кафе и ресторанов соответственно. Близость итогов не доказывает одинаковую локальную полноту.
Суммы счётчиков вокруг центров сетки отличаются от числа уникальных объектов: соседние круги могут пересекаться.

- Основной счётчик включает кафе и рестораны по классификации соответствующего источника.
  Вариант с фастфудом проверяется отдельно; заведения считаются одинаково независимо от размера и концепции.
- Образование измерено в 2026 году и исключено из модели, корреляций и типологии 2019 года.
  Парковочные ёмкости 2019 года сохранены и для 2026-го из-за отсутствия сопоставимого нового слоя.
- Магазины, услуги и транспортные входы — признаки окружения. Потоки покупателей и пассажиров не измерены.
- Все радиусы и расстояния считаются **по прямой в UTM 37N**. 300 м не равны пяти минутам ходьбы:
  реки, ограждения, переходы и железные дороги в маршрутах не учитываются.

Состав слоёв и происхождение: [data/README.md](../data/README.md).

## Расчёт и валидация

Пуассоновская GLM с лог-ссылкой использует `log1p(min(x, c))` для счётчиков и линейные расстояния в км.
Порог `c` — 99-й перцентиль **обучающих** строк; стандартизация также обучается только на них.
Для данных 2019 года признаки: магазины, услуги, выходы метро, остановки, парковочные места,
спортзалы, расстояния до метро и Красной площади. В 2026 году добавлено образование.

Внешняя проверка: шесть фолдов из блоков {v['block_m']}×{v['block_m']} м. Обучающие центры ближе или равные
{v['buffer_m']} м от проверочных исключены. Это устраняет общие объекты в кругах до 400 м, но не гарантирует
отсутствия пространственной зависимости на больших расстояниях. Внутри каждого обучающего набора проводится
отдельная пространственная проверка с таким же буфером для выбора α из {v['alpha_grid']}.
Проверочные ответы не участвуют ни в выборе α, ни в обучении преобразований.

Процедура повторена {v['repeats']} раз (seeds 0–49). Прогнозы усредняются отдельно для радиусов 250, 300 и 400 м.
**D² пуассоновской девиансы** усреднённого прогноза при 300 м: **{v['d2']:.3f}** для 2019 года и
**{now['d2']:.3f}** для 2026 года. По отдельным разбиениям: {repeated_range(v['repeat_d2_range'])}
и {repeated_range(now['repeat_d2_range'])}. D² не является обычным R² или вероятностью успеха бизнеса.
Со слоями окружения 2019 года на счётчиках OSM 2026 D² = {now['d2_2019_footfall']:.3f}.

Диагностические модели ниже используют одно внешнее разбиение (seed=0), поэтому эти числа отличаются от
метрики усреднённых прогнозов. Основная GLM выбрана ради интерпретируемости. Таблица не является независимой
оценкой победителя дополнительного поиска моделей.

{benchmark}

Для каждого радиуса остаток масштабируется:

`score_r = (N_r - mu_r) / sqrt(mu_r + mu_r² / theta_r)`

`theta_r = sum(mu_r²) / sum((N_r - mu_r)² - mu_r)` при положительном знаменателе;
иначе используется пуассоновский предел (`theta = infinity`). Итоговая оценка — среднее трёх таких
остатков. Это описательная шкала ошибок прогноза, а не нормальный z-критерий. Радиусы коррелируют;
три оценки не являются независимыми подтверждениями.

Правило допуска: вход станции в 500 м, не менее 10 магазинов и услуг, прогноз не ниже медианы сетки
на двух радиусах из трёх. Оно должно выполняться и для усреднённых прогнозов, и минимум в
{percent(v['minimum_eligibility_frequency'])} повторов. Из допущенных участков с отрицательной оценкой
выбираются первые десять **по неокруглённым значениям**. 80% — явно выбранный порог отбора,
не уровень статистической значимости. Частота допуска и частота попадания в десятку имеют разные смыслы.

## Условные контрасты признаков

Для счётчика сравниваются указанные значения `x → 2x`; исходное `x` — округлённая вверх медиана
положительных значений. Точное изменение прогноза:

`100 * (exp(beta * (log1p(min(2*x,c)) - log1p(min(x,c)))) - 1)`

Здесь beta — коэффициент до стандартизации. Эффект зависит от исходного счётчика и обрезки;
единого эффекта «удвоения магазинов» для всех участков нет. Остальные признаки фиксируются.

{effects_table(summary, True)}

Интервалы получены 300 повторениями блочного бутстрэпа с повторным обучением преобразований, но при
фиксированном выбранном α = {summary['alpha']:g}, семействе модели и исходных значениях контрастов.
Они не учитывают неопределённость выбора спецификации. Интервал, содержащий ноль, не доказывает отсутствия
связи. Контрасты описывают условную ассоциацию, а не причинный эффект строительства метро или открытия магазинов.

## Список для проверки: данные 2026 года

Прогнозы и наблюдения в таблице относятся к 300 м; оценка объединяет три радиуса. Допуск и попадание
в десятку — частоты по {v['repeats']} разбиениям. 10–90% — перцентили между разбиениями,
**не доверительный интервал** и не диапазон будущей прибыли.

{short_table(scores, 2026, True)}

Более строгая отметка устойчивости требует попадания в десятку минимум в 80% разбиений, места не ниже
12-го на каждом радиусе, сохранения в десятке с фастфудом и в десятке со слоями окружения 2019 года.
Сейчас ей соответствуют: **{robust_names}**. Отсутствие отметки само по себе не означает плохой участок;
оно показывает чувствительность к конкретной проверке. Проверки используют те же данные и не являются
независимыми подтверждениями коммерческой привлекательности.

Сильные отрицательные оценки вне итогового допуска:

{excluded_table(scores, True)}

Отрицательной оценки недостаточно для попадания в список. Полные результаты всех участков остаются в
[cell_scores.csv](cell_scores.csv) и [интерактивной странице](report_ru.html).

«Лефортово» открылась [27 марта 2020 года]({STATION_SOURCE}), а не в 2023-м.
По двум снимкам нельзя определить начало отклонения или утверждать, что кафе не успели отреагировать
на новую станцию. Это относится и к объяснениям результатов у Митьково.

![Отклонения и итоговый отбор, 2026](figures/fig10_opportunity_map_2026.png)

## Сопоставление источников 2019 и 2026 годов

Группы выбраны по остатку 2019 года, от минимального к максимальному. Последний столбец — отношение
сумм записей OSM к суммам записей реестра, **не измеренный темп роста рынка**.

{source_table(summary, True)}

Различия полноты и классификации, отбор по начальному остатку и возврат к среднему могут создавать
видимость закрывающегося разрыва. Поэтому эта таблица не валидирует бизнес-рекомендации.

Дополнительная регрессия объясняет `log((N2026 + 1)/(N2019 + 1))` через `log(N2019 + 1)` и
`log(mu2019)`. При одинаковом исходном счётчике удвоение прогноза связано с изменением условного
**геометрического среднего `N2026 + 1`**; оценка и границы 95% блочного интервала:
**{interval(summary, 'slope')}**. После добавления расстояния до центра:
**{interval(summary, 'distance_slope')}**. Это не изменение арифметического среднего числа кафе.
Бутстрэп условен на уже рассчитанных прогнозах; источник ошибок и повторное обучение модели не включены.

{type_table(summary, True)}

Названия кластеров описательные; исходное число кафе участвует в кластеризации. При k=4 силуэт
{summary['silhouette_k4']:.3f}, поэтому группы слабо разделены. Таблица по типам и поправка на расстояние
не выделяют эффекты пандемии, войны, санкций, туризма или ухода сетей.

Ретроспективный список по данным 2019 года, рассчитанный исправленным методом сейчас:

{short_table(scores, 2019, True)}

Это не прогноз, выпущенный в 2019 году. Сравнение его счётчиков с OSM не подтверждает реальные открытия
или закрытия. Для временной валидации нужен единообразный продольный источник и заранее заданная процедура.

## Практический вывод и воспроизведение

Список пригоден для выбора участков, на которых стоит сверить реестр, пройти маршруты, проверить входы,
посчитать пешеходов и изучить помещения, аренду и концепцию заведения. Данных для оценки окупаемости нет.
Сильные положительные остатки также не доказывают избыточную конкуренцию: возможны пропущенные офисы,
отели, фуд-холлы, различия единиц учёта и ошибки модели.

`python scripts/run_analysis.py` выполняет notebook 03 и пересобирает оба отчёта, README и HTML.
Данные уже сохранены, сетевые запросы для расчёта не нужны. Настройки всех 900 внешних моделей на год
записаны в `cv_folds_2019.csv` и `cv_folds_2026.csv`; частоты — в `screening_stability_*.csv`.
Версии этого запуска: {runtime or 'см. summary.json после полного запуска'}.
Код и проверки: [model.py](../src/moscow_cafes/model.py), [test_model.py](../tests/test_model.py).
"""
    return f"""<!-- Generated by scripts/build_markdown_reports.py; edit the builder, not this file. -->
# Café counts and candidate areas in central Moscow

This analysis predicts **recorded café and restaurant counts**, using the surroundings of 364 grid cells
within 6 km of Red Square. A negative residual means fewer records than the model predicts. It does not
establish unmet consumer demand, available premises or the profitability of a new café. The output is a
fieldwork shortlist. [Русская версия](REPORT.ru.md) · [Interactive page in Russian](report_ru.html).

## Data and comparability

The sources are a 2019 city register and OpenStreetMap dated **{summary['osm_date']}**, containing
{summary['competitors_within_6km']:,} and {now['competitors_within_6km']:,} cafés and restaurants within 6 km.
Similar totals do not establish comparable local coverage. The two sources have different classifications
and completeness. Differences are not verified openings, closures or market growth. Neighbourhood count
sums differ from unique venue totals because nearby catchments can overlap.

The primary target counts cafés and restaurants equally; fast food is a separate sensitivity analysis.
Education measured in 2026 is excluded from the 2019 model, correlations and typology. The 2026 model
uses it, but retains 2019 parking capacities for lack of a comparable newer layer. Infrastructure and shops
are proxies, not observed pedestrian or passenger flows. See [data provenance](../data/README.md).

All distances use UTM 37N and **straight-line circles**. A 300 m radius is not a five-minute walking area;
rivers, railway tracks, private access and crossings are not routed.

## Model, validation and screening

The primary Poisson GLM has a log link, `log1p(min(x,c))` count features, and linear distances in km.
The 99th-percentile caps and standardisation are fitted on training rows only. Historical predictors are
shops, services, metro exits, stops, parking spaces, gyms and distances to metro and Red Square.
Contemporaneous education is added in the 2026 model.

Outer validation uses six folds of {v['block_m']}×{v['block_m']} m blocks, excluding training centres within
{v['buffer_m']} m of test centres. This removes shared objects between circles of up to 400 m, not all
longer-range spatial dependence. Each outer training subset tunes α from {v['alpha_grid']} using its
own inner six-fold spatial validation and the same buffer. Held-out responses do not affect preprocessing
or penalty selection for their predictions.

We repeat the procedure {v['repeats']} times, seeds 0–49, and average out-of-fold predictions at each radius.
At 300 m, **Poisson-deviance D²** of the averaged prediction is **{v['d2']:.3f}** for 2019 and
**{now['d2']:.3f}** for 2026. Individual-split ranges are {repeated_range(v['repeat_d2_range'])} and
{repeated_range(now['repeat_d2_range'])}. D² is not ordinary R² or a business-success probability.
For 2026 counts with historical surroundings and no future education, D² = {now['d2_2019_footfall']:.3f}.

Diagnostic benchmarks use one outer split, seed 0, rather than the averaged predictions above:

{benchmark}

The primary GLM is chosen for interpretability. This table is not a further model-selection process with
an independently evaluated winner. Each radius uses a descriptive, NB2-scaled residual:

`score_r = (N_r - mu_r) / sqrt(mu_r + mu_r² / theta_r)`

The moment estimate is `theta = sum(mu²) / sum((N-mu)²-mu)` when the denominator is positive;
otherwise the Poisson limit is used. The final score averages the three radius scores after averaging
predictions. It is not a calibrated normal z statistic, and the radii are correlated.

A cell passes a repeat if at least two radii have a station entrance within 500 m, at least 10 shops plus
services, and an expected count at or above the grid median. Final eligibility requires this rule on the
averaged predictions and in at least {percent(v['minimum_eligibility_frequency'])} of repeats. We select up
to ten negative scores using **unrounded** values. The 80% cutoff is a declared screening policy, not a
significance level. Eligibility frequency and top-ten frequency describe different events.

## Conditional feature contrasts

For each count, the baseline is the rounded-up median positive count, explicitly displayed as `x → 2x`.
The correct cap-aware contrast is
`100 * (exp(beta * (log1p(min(2*x,c)) - log1p(min(x,c)))) - 1)`, with the unscaled coefficient beta.
It depends on the starting count and cap; there is no universal effect of doubling a count.

{effects_table(summary, False)}

The 300 block-bootstrap replicates refit preprocessing, but condition on the specification, baseline
contrasts and fixed selected α = {summary['alpha']:g}. They do not account for model-selection uncertainty.
A zero-covering interval does not establish absence of association. These are conditional model contrasts,
not causal effects of adding shops, services or stations.

## The 2026 fieldwork shortlist

Counts, expectations and prediction ranges refer to 300 m; scores combine three radii. Eligibility and
top-ten frequencies describe the {v['repeats']} splits. The 10th–90th percentiles describe split sensitivity,
**not confidence intervals** or future commercial outcomes.

{short_table(scores, 2026, False)}

A stricter sensitivity badge requires top-ten membership in at least 80% of repeats, rank at most 12 at
all three radii, and top-ten membership both with fast food and with historical surrounding layers.
Cells passing all these checks: **{robust_names}**. These checks reuse data and are not independent
confirmations of commercial potential; failing one is not proof of an unsuitable site.

Strong negative residuals outside final eligibility remain visible:

{excluded_table(scores, False)}

Lefortovo station opened on [27 March 2020]({STATION_SOURCE}), not in 2023. Two snapshots cannot date the
onset of a residual or show that cafés have not had time to respond to a station opening. The same
limitation applies to proposed explanations of the Mitkovo results.

![2026 residuals and eligible shortlist](figures/fig10_opportunity_map_2026.png)

## Comparing the 2019 register and 2026 OSM

Quintiles are defined by 2019 residuals, lowest first. The final column compares sums of source records,
not market growth. Coverage changes, baseline selection and regression to the mean can produce apparent
convergence, so this comparison does not validate unmet demand or business recommendations.

{source_table(summary, False)}

The exploratory regression models `log((N2026+1)/(N2019+1))` using `log(N2019+1)` and `log(mu2019)`.
At an equal baseline count, doubling the prediction is associated with a change in the conditional
**geometric mean of `N2026+1`**. Estimate, lower and upper 95% block-bootstrap limits:
**{interval(summary, 'slope')}**; adding distance to Red Square gives
**{interval(summary, 'distance_slope')}**. This is not an arithmetic mean count-growth effect. Bootstrap
intervals condition on existing predictions and do not refit the count model or model source errors.

{type_table(summary, False)}

The cluster names are descriptive, and baseline café counts enter the clustering. The k=4 silhouette is
{summary['silhouette_k4']:.3f}, indicating weak separation. Cluster differences and distance adjustment do
not separately identify the effects of the pandemic, war, sanctions, tourism or chain exits.

Historical shortlist, reconstructed now using the corrected method:

{short_table(scores, 2019, False)}

This is not a forecast issued in 2019. A consistent longitudinal source and a prespecified evaluation
would be needed to test real openings, closures and the usefulness of the screening rule.

## Practical conclusion and reproduction

Use the list to check records, walking access, pedestrian flows, premises, rents and the proposed concept
on site. Positive residuals likewise do not prove oversupply: omitted offices, hotels, food halls, counting
units and model error may explain them. These data cannot establish payback or profitability.

Run `python scripts/run_analysis.py` to execute notebook 03 and rebuild both reports, README and HTML.
Committed snapshots allow offline computation. `cv_folds_2019.csv` and `cv_folds_2026.csv` record all 900
outer fits per year; `screening_stability_*.csv` contains all-cell diagnostics.
Runtime: {runtime or 'see summary.json after a full run'}.
Implementation: [model.py](../src/moscow_cafes/model.py); regression tests: [test_model.py](../tests/test_model.py).
"""


def build_readme(summary):
    old, new = summary["validation"]["d2"], summary["now"]["d2"]
    return f"""<!-- Generated by scripts/build_markdown_reports.py. -->
# Café counts and candidate areas in central Moscow

IBM Data Science Professional Certificate capstone (Coursera), started in 2019 and revisited in 2026.
[По-русски ниже](#по-русски).

A count model compares 364 grid cells within 6 km of Red Square. It predicts recorded cafés and
restaurants from nearby shops, services, infrastructure and distances. Negative residuals identify areas
for checking data and visiting in person. They **do not establish unmet demand or business profitability**.
Catchments are 250, 300 and 400 m straight-line circles, not walking isochrones.

![2026 count residuals and fieldwork shortlist](report/figures/fig10_opportunity_map_2026.png)

The analysis uses nested spatial validation with an 800 m buffer and 50 repeated block assignments.
Caps and scaling are fitted on training data; education measured in 2026 is excluded from the historical
model. Poisson-deviance D² of averaged out-of-fold predictions: **{old:.3f}** (2019), **{new:.3f}** (2026).
The shortlist includes split frequencies and prediction ranges. D² is not a business-success probability.
The 2019 register / 2026 OSM comparison does not measure verified openings, closures or market growth.

## Read and reproduce

- [Full report](report/REPORT.md) · [Отчёт на русском](report/REPORT.ru.md).
- [Interactive Russian page](report/report_ru.html): download and open in a browser.
- [Notebook 03](notebooks/03_cafe_location_analysis.ipynb): executed analysis and figures.
- [Data provenance](data/README.md), [count model](src/moscow_cafes/model.py), [tests](tests/).
- `report/`: complete scores, shortlists, split diagnostics, fold choices, figures and maps.

```bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
pytest
python scripts/run_analysis.py
```

The full run uses committed data offline and takes several minutes, depending on the machine. It executes
the notebook, then rebuilds both Markdown reports, README and the interactive HTML. For text-only changes,
run `python scripts/build_markdown_reports.py` and `python scripts/build_report_page.py` after updating
their builders. Runtime versions are recorded in `report/summary.json`.

Notebooks 01 and 02 are historical archives of the 2019 collection and Foursquare exploration. Their
obsolete APIs are not part of the reproduction path. The current analysis reprojects original WGS84
coordinates to UTM 37N; it does not use the archived UTM 33 distances or district selection logic.
`scripts/fetch_osm_data.py` optionally replaces the OSM snapshot; changing data requires a complete rerun.

## Data and license

- Moscow Open Data, [data.mos.ru](https://data.mos.ru), 2019 extracts; restored registers from the project backup.
- OpenStreetMap snapshot {summary['osm_date']}, © OpenStreetMap contributors,
  [ODbL](https://opendatacommons.org/licenses/odbl/).
- Grid addresses from Yandex Geocoder (2019), with Russian address labels from OSM (2026).
- Code: GNU GPL v3, see [LICENSE](LICENSE).

## По-русски

Модель оценивает число записей о кафе и ресторанах на 364 участках центра Москвы. Отклонение от прогноза
помогает выбрать места для проверки; оно не доказывает свободный спрос или прибыльность нового кафе.
Радиусы считаются по прямой. Пешеходный поток, аренда и доступные помещения не измерены.

Исправлены эффекты `log1p` с обрезкой, утечка будущего слоя в историческую модель, подбор регуляризации
и пространственная проверка. Используются вложенная валидация, буфер 800 м и 50 разбиений;
публикуются частоты допуска и попадания в десятку. Порог допуска 80% — правило отбора, не вероятность успеха.
D² усреднённых прогнозов: **{old:.3f}** и **{new:.3f}**. Результаты двух источников не выдаются за реальную
историю открытий и закрытий. Подробности и новый список — в [отчёте](report/REPORT.ru.md).
"""


def build():
    summary, scores = load()
    for ru, name in ((False, "REPORT.md"), (True, "REPORT.ru.md")):
        (REPORT / name).write_text(build_report(summary, scores, ru), encoding="utf-8")
    (ROOT / "README.md").write_text(build_readme(summary), encoding="utf-8")


if __name__ == "__main__":
    build()
